exports.seed = function(knex, Promise) {
  //DELETES EXISTING ENTRIES
  return knex('foods').del()
    .then(() => {
      return knex('foods').insert([
        {
          food_name: 'artichokes',
          created_by: 1,
          mar: true,
          apr: true,
          may: true,
          jun: true,
          sep: true,
          oct: true,
          nov: true,
          dec: true

      },
      {
        food_name: 'arugula',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'asparagus',
        created_by: 1,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true
      },
      {
        food_name: 'beets',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'bitter melon',
        created_by: 1,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'bok choy',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'broccoli',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'broccoli rabe',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'brussels sprouts',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'burdock',
        created_by: 1,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'cabbage',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'cactus pads',
        created_by: 1,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true
      },
      {
        food_name: 'cardoons',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'carrots',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'cauliflower',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'celeriac',
        created_by: 1,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'celery',
        created_by: 1,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'chard',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'chicory',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'collard greens',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'corn',
        created_by: 1,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true
      },
      {
        food_name: 'cress',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'cucumbers',
        created_by: 1,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true
      },
      {
        food_name: 'dandelion greens',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true
      },
      {
        food_name: 'eggplant',
        created_by: 1,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true
      },
      {
        food_name: 'endive',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'fava beans',
        created_by: 1,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true
      },
      {
        food_name: 'fava greens',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true
      },
      {
        food_name: 'fennel',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'garlic',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'ginger',
        created_by: 1,
        aug: true,
        sep: true,
        oct: true,
        nov: true
      },
      {
        food_name: 'green beans',
        created_by: 1,
        jun: true,
        jul: true,
        aug: true,
        sep: true
      },
      {
        food_name: 'green garlic',
        created_by: 1,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true
      },
      {
        food_name: 'horseradish',
        created_by: 1,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true
      },
      {
        food_name: 'jicama',
        created_by: 1,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'kale',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'kohlrabi',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'lambsquarters',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'leeks',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'lettuce',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'mizuna',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'mushrooms',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'mustard greens',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'nettles',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true
      },
      {
        food_name: 'okra',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        dec: true
      },
      {
        food_name: 'onions',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'orach',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'parsnips',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'pea shoots',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true
      },
      {
        food_name: 'peas',
        created_by: 1,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true
      },
      {
        food_name: 'peppers, chile',
        created_by: 1,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'peppers, sweet',
        created_by: 1,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'potatoes',
        created_by: 1,
        jun: true,
        jul: true,
        aug: true,
      },
      {
        food_name: 'purslane',
        created_by: 1,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true
      },
      {
        food_name: 'radishes',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'rutabas',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'salsify',
        created_by: 1,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'scallions',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'shallots',
        created_by: 1,
        may: true,
        jun: true,
        jul: true
      },
      {
        food_name: 'shelling beans',
        created_by: 1,
        aug: true,
        sep: true,
        oct: true
      },
      {
        food_name: 'spinach',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'sprouts',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'squash, summer',
        created_by: 1,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true
      },
      {
        food_name: 'squash, winter',
        created_by: 1,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'sunchokes',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'sweet potatoes',
        created_by: 1,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'taro root',
        created_by: 1,
        jan: true,
        feb: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'tatsoi',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'tomatillos',
        created_by: 1,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true
      },
      {
        food_name: 'tomatoes',
        created_by: 1,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true
      },
      {
        food_name: 'turnips',
        created_by: 1,
        jan: true,
        feb: true,
        mar: true,
        apr: true,
        may: true,
        jun: true,
        jul: true,
        aug: true,
        sep: true,
        oct: true,
        nov: true,
        dec: true
      },
      {
        food_name: 'yacon',
        created_by: 1,
        nov: true,
        dec: true
      }
    ])
      .then(() => {
        return knex.raw("SELECT setval('foods_id_seq', (SELECT MAX(id) FROM foods));");
      });
    });
};
